### ISSUE TITLE
Algorithms

### ISSUE THREAD

**Issue by TheBestTvarynka** [TheBestTvarynka/crypto-helper#4]
the list of the crypto algorithms that will be good to support:

- [ ] argon2
- [x] bcrypt
- [x] sha384

...

**Comment by jayanth-kumar-morem** [comment]
Hi @TheBestTvarynka , I would like to take this one up. Can you assign me to this.

**Comment by TheBestTvarynka** [comment]
@jayanth-kumar-morem  
I've assigned you to #16. when you finish it, you can take this task

**Comment by Jujumba** [comment]
Hello, got some spare time to finally close this issue. Guess I'd implement `argon2` in a week or so.
@TheBestTvarynka

**Comment by TheBestTvarynka** [comment]
@Jujumba 
good, ping me when you need a review or any help
