### ISSUE TITLE
Inprove simple output component

### ISSUE THREAD

**Issue by TheBestTvarynka** [TheBestTvarynka/crypto-helper#7]
Look at this component: https://github.com/TheBestTvarynka/crypto-helper/blob/main/src/common/simple_output.rs#L61 
It's a simple output component that can render bytes in different formats. On the web app, it looks like this:
![simple_output_demo-2023-04-03_23 00 57](https://user-images.githubusercontent.com/43034350/229615144-3809f0d7-7771-43bc-b045-e307a176fc78.gif)

In the scope of this issue, you need to improve this component:

- [x] add decimal format
- [x] add binary format

**Comment by jayanth-kumar-morem** [comment]
Hi @TheBestTvarynka , I would like to take this one up. Can you assign me to this.

**Comment by jayanth-kumar-morem** [comment]
#21 solves this issue.
cc: @TheBestTvarynka
